### ISSUE TITLE
: Remove word legacy form the “Legacy_CoEDashboard_yyyyMM.pbit ”. 

### ISSUE THREAD

**Issue by rizwanasif1** [MicrosoftDocs/power-platform#1033]
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use

![image](https://user-images.githubusercontent.com/33668478/145889856-64c59d95-f861-4a64-95b9-89df59d9e7a8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c365c412-6317-0eb4-b7a1-0a5cc84b1cbd
* Version Independent ID: 9e39031d-66dd-bf29-1b5c-a93608badc60
* Content: [Set up the Power BI dashboard - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#which-dashboard-to-use)
* Content Source: [power-platform/guidance/coe/setup-powerbi.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-powerbi.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Thanks for the feedback! We are updating our docs for the January release, and I have fixed this locally for the next docs update now! We have updated the name of our Power BI dashboards now https://github.com/microsoft/coe-starter-kit/issues/1652

I'm closing out this issue here as it's this change will go live with the January release and is tracked in our coe-starter-kit github repo.
