### ISSUE TITLE
Unable to get the desired output from advanced-bot-framework-composer-example1

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftDocs/power-platform#1320]
Hello, 

While trying to perform the exercise in my own environment. I'm unable to get a proper response from the bot. I instead get the following code instead of the adaptive card :
![image](https://user-images.githubusercontent.com/47213023/175748943-646a433c-209a-4f0b-ac4a-7c8a8ef49c24.png)

Note that I am using the free trial of the Power virtual agents and the latest Bot framework composer app. 
I double-checked the code that is being pasted under the Bot-responses section. But it's still the same. Am I missing something here? Please help.

Thanks and Regards.

**Comment by v-alarioza** [comment]
Hi @junnhssn, thanks for your report!

I think the issue may be that you've placed the response in the response editor, instead of the code editor.

❌Response editor:
<img width="274" alt="Screenshot_448" src="https://user-images.githubusercontent.com/94562440/175973889-8e3f5d5c-b603-4b9a-ac20-d640677ef205.png">

✔Code editor:
<img width="253" alt="Screenshot_447" src="https://user-images.githubusercontent.com/94562440/175973915-911659cc-e277-4b6a-9d46-2e486de65a6f.png">

The instructions don't make this super obvious, so I'll look into improving that.

Let me know if this solves your problem!

**Comment by junnhssn** [comment]
Hey, thanks for the quick response.  The issue was indeed the one you have mentioned above. I was able to get it working by placing the code in code editor. I'll be closing the issue now, thanks again.
