### ISSUE TITLE
SharePoint custom form  Makers Security Group not working

### ISSUE THREAD

**Issue by robertobudelo-armacell** [MicrosoftDocs/power-platform#1474]
This is related to https://learn.microsoft.com/en-us/power-platform/admin/admin-manage-apps#distinguish-microsoft-sharepoint-custom-form-makers-from-general-environment-makers

The second step asks to install the following App Source Solution:
https://appsource.microsoft.com/en-GB/product/dynamics-365/mscrm.sharepointcustomformmaker

Unfortunately, this solution is incomplete as it only contains the "SharePoint custom form Maker role", but does not include the "SPO custom form entity" as referenced in https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWCK2q

Therefore, users with this security role will create SPO forms on the previously defined environment.

Manually  creating the SPO custom form entity and creating a new SR role with user-only CRUD rights establishes the correct outcome.

Please update the AppSource App.

**Comment by jimholtz** [comment]
@robertobudelo-armacell 
Sorry for the delayed response. Here's what the product team communicated:

1. The solution is expected to only have the “SharePoint custom form Maker” security role. 

This provides a mechanism for Power Platform to distinguish users with only privileges SharePoint Custom Form privileges from general Environment Makers which can make any Power Platform resource. To observe the distinction a customer will have to configure their SharePoint custom forms to save to an environment other than the default environment (because in the default environment every user has the Environment Maker security role). 

2. SharePoint custom forms are not explicitly bound to a “SPO custom form entity” in Dataverse. 

Power Platform delegates granular privilege checks to SharePoint. For example, a user with the “SharePoint Custom Form Maker” role which attempts to create a custom form causes the platform to check with SharePoint that the user has edit privileges in the corresponding SharePoint site.
