### ISSUE TITLE
Power Platform CLI only available on VS Code (GUI) or windows

### ISSUE THREAD

**Issue by MCKevmeister** [MicrosoftDocs/power-platform#1585]
[Enter feedback here]

I use mac OS, and I use webstorm, i do not use Visual Studio Code as it is not an IDE and does not provide all the functionality that I need. Please allow me to use the CLI tool on mac without Visual Studio Code and make a Jetbrains plugin for azure CLI. Provide a cross platform CLI tool. Or else remove CLI from the name of this tool as its not a CLI tool, its a GUI tool that only works with Visual Studio Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Version Independent ID: 5446bda4-9257-9a56-ff6b-b62a82b79132
* Content: [Microsoft Power Platform CLI - Power Platform](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction)
* Content Source: [power-platform/developer/cli/introduction.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/developer/cli/introduction.md)
* Service: **power-platform**
* Sub-service: **developer**
* GitHub Login: @kkanakas
* Microsoft Alias: **jdaly**

**Comment by kkanakas** [comment]
You can download the MacOS pac cli from the following location 
https://www.nuget.org/packages/Microsoft.PowerApps.CLI.Core.osx-x64

**Comment by davidjenni** [comment]
@MCKevmeister we've been sim-shipping the pac CLI for a year+ for Windows (net48 fullFx) and linux/macOS (net6 intel/x64, no native M1/arm64 support yet). Installing from nuget.org is a bit more cumbersome for most users, hence we're not advertising that path much; our best practice installation is indeed via the VSCode extension.
Note that due to limitations in the nupkg format (it does not preserve unix file attributes), you'll need to `chmod +x tools/pac` after extracting the package. No plans to produce .dmg packages either.

**Comment by MCKevmeister** [comment]
So install vs code, install the extension, copy the installed extension to a different folder, uninstall vs code and add extension to path? How do you think that is this is the preferable solution for a mac developer who doesn't use VS code to just allowing the cli tool to be install via the CLI and publishing how to do so?

It sounds like you know how to do so, yet won't publish it because it would allow people to not install VS code, so marketing is blocking development?
