### ISSUE TITLE
Issue about the `pac canvas pack` command

### ISSUE THREAD

**Issue by stupidWall** [MicrosoftDocs/power-platform#1623]
### Prerequisite 
- I have a solution that includes canvas powerapps
- I implemented a code component
- I imported my code component into my solution that includes the canvas app, and I used the code component in my canvas app
- I exported the solution, so I manage the source code of the solution
- My PowerPlatform CLI Version 1.19.4

### Issue
When I imported my solution into my environment and try to edit my app, something was wrong:
![image](https://user-images.githubusercontent.com/17538999/203723806-8e7d138a-eeac-4b0b-9a6d-9afc17f60d0d.png)

In the process of this import, I used this command to generate the .msapp file from the warehouse source code：
`pac canvas pack --msapp myapp.msapp --source myapp` 

This problem has troubled me for several days. After my repeated verification, I found that this problem will occur after executing the above command to complete the upload under the mac OS system. Still, there will be no such problem under the window system. 

Everything works fine under the windows system.

So my question is why under the macOS system, when my canvas app contains code compoent, the `.msapp` file generated by the `pac canvas pack` command has this problem?

Does anyone know how to fix it?

**Comment by JimDaly** [comment]
@stupidWall 
Issues in this repo are so that people can provide feedback on the documentation.

You should submit your feedback related to the page where you expected to find information, like this one [pac canvas](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/canvas). There is a button at the bottom of the page that will create an issue and assign it to the owner of the topic.

Also, in that topic I notice this:

> **Open source**
> The canvas commands in Microsoft Power Platform CLI are open source. Discuss improvements, raise issues, and access the code from [Power Apps language tooling repository](https://github.com/microsoft/PowerApps-Language-Tooling).

I think that is where you should raise this issue. I'm going to close this one.
