### ISSUE TITLE
pac solution unpack deletes solution attachments.

### ISSUE THREAD

**Issue by kousikchatterjee** [MicrosoftDocs/power-platform#1711]
I am trying to unpack a solution which contains some solution attachments for email templates, those are getting deleted after every 2nd unpack command.

Please find the detailed steps:
1. Downloaded a solution using pac solution export.
2. Unpacked in a local folder and commited to repos.
3. Solution attachments for each email templates contains two files, one with the actual name another one without space and special char, extension.
4. Downloaded another version of the same solution and unpacked into the same local folder with allow delete and allow write flag as true.
5. The original file from the solution attachment folder got deleted showing as "there are unnecessary files".
6. Tried to pack the solution to deploy to another env but got failed with dependency error for the same deleted file.
7. Unpacked the same zip file again and this time the solution attachments contains two files as it was there during the first unpack.
8. And this cycles keeps continuing.

To export, checkin to repos, pack and deploy to another env I need to run the unpack and commit to repos two times.

**Comment by JimDaly** [comment]
Issues reported against the documentation must include some specific feedback to be actionable, preferably relating to a specific topic.

Issues for this repository must address the documentation content or functionality. 

This issue seems to be a request for technical support. We do not have the resources to troubleshoot issues. If you need help, please contact technical support.
