### ISSUE TITLE
Per App license clarification

### ISSUE THREAD

**Issue by PSJanne** [MicrosoftDocs/power-platform#192]
Just to be sure I need to understand how we could build an App for healthcare professionals with using Per App Plan license model. So can we combine some critical use scenarios and sub-processes into one single App for specific roles in hospital (like processes related to providing care). For example is this Emergency Response App something that would be built with one Per App license; https://www.youtube.com/watch?v=H1u6SYt3UsQ&feature=youtu.be. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#feedback)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by jimholtz** [comment]
@PSJanne 
It is difficult to provide licensing guidance in documentation comments because to understand license requirements we need to be more involved. 
As a general guidance, per app license allows access to up to 2 apps and a portal to the user. So they can build a solution as long as it is using a max of two apps and a portal. Also each individual user of the app/portal must be covered and appropriate capacity should be assigned to the environment.
