### ISSUE TITLE
Issues with setting up Audit Logs

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/power-platform#209]
Hi

In Turning the audit log on and off in this section ( - Important
Office 365 Audit Log search must be turned on for the Audit Log connector to work. More information: Turn audit log search on or off.) References this section of docs.microsoft.com - https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide which says :-

Before you begin
You have to be assigned the Audit Logs role in Exchange Online to turn audit log search on or off in your Microsoft 365 organization. By default, this role is assigned to the Compliance Management and Organization Management role groups on the Permissions page in the Exchange admin center. Global admins in Microsoft 365 are members of the Organization Management role group in Exchange Online.

 Note

Users have to be assigned permissions in Exchange Online to turn audit log search on or off. If you assign users the Audit Logs role on the Permissions page in the Security & Compliance Center, they won't be able to turn audit log search on or off. This is because the underlying cmdlet is an Exchange Online cmdlet.

Which is OK if you are in a dev environment but in a production environment is not so easy to achieve if you have not got E5 licences.  

This is not mentioned anywhere.

IS there another way of doing this ?

Regards

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Office 365 Audit Log is a tenant setting, which is switched on for your entire tenant, it sits above the concept of environments in the Power Platform. 
We are only using a custom connector to connect to it, but are otherwise reliant on pre-requisites and settings of the Office 365 Audit Log.

**Comment by NPrice99** [comment]
Hi Manuela

Agreed, but for the custom connector to work Audit Logs need to be switched on for which you need an E5 licence and you need permissions so you have to be assigned the Audit Logs role in Exchange Online to turn audit log search on or off in your Microsoft 365 organization.

Or have I missed something ?

Regards

Nigel

**Comment by manuelap-msft** [comment]
I think I'm missing the part where this requires an E5 license? Detailed pre-requisites for the Office 365 Audit Log can be found here: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-begin and what's included in all the plans is listed here https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

Audit logs for all plans that include Basic Audit are retained for 90 days. Because E5 includes Advanced Audit, audit logs are retained for up to one year. 

Yes, you do need permission to view the Audit Log which is not included in the Power Platform Service Admin Role. 

You have to be assigned the View-Only Audit Logs or Audit Logs role in Exchange Online to search the audit log. By default, these roles are assigned to the Compliance Management and Organization Management role groups on the Permissions page in the Exchange admin center. Note global administrators in Office 365 and Microsoft 365 are automatically added as members of the Organization Management role group in Exchange Online. To give a user the ability to search the audit log with the minimum level of privileges, you can create a custom role group in Exchange Online, add the View-Only Audit Logs or Audit Logs role, and then add the user as a member of the new role group. https://go.microsoft.com/fwlink/p/?LinkID=730688

**Comment by NPrice99** [comment]
Hi Manuela

Thanks for the clarification.

Does the prerequisites for the CoE need to include the requirement that You have to be assigned the View-Only Audit Logs or Audit Logs role in Exchange Online to search the audit log ? (or did I miss it)

Regards

Nigel

**Comment by manuelap-msft** [comment]
The Center of Excellence (CoE) Starter Kit will work without this Audit Log, but the usage information (app launches, unique users) in the Power BI dashboard will be blank. It is therefore not a pre-requisite for the whole kit.

On the Collect Audit Log data page https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog we do call out Global tenant admins have access to the audit logs by default and can grant access to the audit logs for other user accounts or groups through the Exchange admin center.

We will include some of the above clarifications with the next release, thanks for your feedback and making the CoE Starter Kit greater!

**Comment by NPrice99** [comment]
Thanks Manuela keep up the outstanding work on the Centre Of Excellence.

I don’t know if it is possible, but it would be good to just be able to run a Powershell script to setup the CoE as setting up is a intricate and time consuming exercise.
