### ISSUE TITLE
Links in 'Govern' section of CoE Starter Kit Dashboard Introduction Page do not open Apps (Deep Dive) or Cloud Flows (Deep Dive)

### ISSUE THREAD

**Issue by tim-truetandem** [MicrosoftDocs/power-platform#2115]
The links in the Govern section of the Introduction Page in the August CoE Starter Kit Dashboard Power BI Report do not link to the corresponding App or Cloud Flow Deep Dive page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3d9f529-ccac-c9f5-8133-a3c31f1a6f3e
* Version Independent ID: 099d9362-d7be-3df2-cab2-0f68e3f28dfd
* Content: [Govern with the CoE Power BI dashboard - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/power-bi-govern)
* Content Source: [power-platform/guidance/coe/power-bi-govern.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/power-bi-govern.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

thank you for letting us know! I've raised this as an issue in the GitHub project that we use to track our development work
https://github.com/microsoft/coe-starter-kit/issues/6401 and we'll address it with the next release.

I'm closing this issue here, as we only track documentation issues here and this is a dev issue. 

Thank you,
Manuela
