### ISSUE TITLE
Audit log access

### ISSUE THREAD

**Issue by tstjohnsfg** [MicrosoftDocs/power-platform#230]
As the Power Platform admin I do not have permissions to search the audit log. If a Global admin of our tenant creates the connection to audit logs using their credentials, should I then be able to continue with the audit log set up? I am currently attempting this and receiving and invalid credentials error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by tstjohnsfg** [comment]
For clarification, I am receiving an error when I 'Test' the Office 365 Audit Logs custom connector

**Comment by manuelap-msft** [comment]
For any issues relating to the CoE Starter kit itself, and not documentation gaps please use https://aka.ms/coe-starter-kit-issues

Before you use the Office 365 Audit Log connector
- Office 365 Audit Log search must be turned on for the Audit Log connector to work. 
- You must have access to the Office 365 Audit Log. The Power Platform Service Admin role does not give you access to the Audit Log. 
- Your tenant must have a subscription that supports unified audit logging. 

In order to use the Audit Log connectors within the CoE Starter Kit, the account/user you are using must have access to the Audit Logs.

**Comment by tstjohnsfg** [comment]
Thanks! Will refer to the link going forward.
