### ISSUE TITLE
Is it Possible to convert 32bit C++ MFC application into 64bit Application using copilot?

### ISSUE THREAD

**Issue by ThejaswiniN** [MicrosoftDocs/power-platform#2343]
Is it Possible to convert the 32bit C++ MFC Application into 64bit Application using GitHub Copilot in Visual studio 2019 IDE?

**Comment by JimDaly** [comment]
@ThejaswiniN 

Issues for this repository are for the product documentation. Tell us how we can improve the documentation for Power Platform applications.

You are asking an open question about possibilities that are out of scope for the products documented using this repository.

Find an appropriate article within the [Microsoft Power Platform documentation](https://learn.microsoft.com/power-platform/), then click the **Feedback** button at the bottom of the page to submit feedback about a specific article.

Closing this since there is nothing actionable for us.
