### ISSUE TITLE
Sync Flows for Apps & Flows not upserting records of Apps / Flows when deleted

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/power-platform#303]
Deployed Core Solution 1.45
Saved Flows as a copy

In the flows 
**Copy of - Admin | Sync Template v2 (Apps)**
**Copy of - Admin | Sync Template v2 (Flows)**
I only see the apps/flows being retrieved using the admin connector so only present flows are being updated / inserted.
On the documentation page it says these flows also flag apps/flows that are deleted but I do not see any update of the CoE entities records setting the _Is deleted_ fields to Yes. Am I missing something?

**Comment by manuelap-msft** [comment]
Good point, let me try and explain!

In previous versions, the sync flows marked apps and flows as deleted - the only way they could do that was by comparing what's in your tenant vs what's in the CDS entities. This was very time consuming, and for large enterprises caused the Sync Flows to run 10+ hours. We have therefore removed this "delete by comparison" logic from the Sync Flows, and instead updated the Audit Log solutions (both Basic and MFA) to capture Delete Power App and Delete Flow events from the Office 365 Audit Log. Those flows update the Deleted fields on the entities now - the logic is now based on audit log events, rather than on comparison.

We are working on a helper flow that marks apps and flows as deleted based on comparison for customers who do not have access to their Audit Logs, or don't have Audit Logging enabled in their tenant. This flow can then be run once a week for example for to minimize performance issues. 

We'll update the documentation to make sure the Sync Flows don't mention marking apps and flows as deleted anymore!

**Comment by m3ngi3** [comment]
Thanks for the update and the info!
I will create a simple helper flow for now 👍

**Comment by manuelap-msft** [comment]
With the latest version, we have added a "[Check Deleted](https://docs.microsoft.com/en-us/power-platform/guidance/coe/release-notes/core-1.52#admin--sync-template-v2-check-deleted)" flow that checks for deleted resources.
