### ISSUE TITLE
How long until security group assignment and membership sync takes effect

### ISSUE THREAD

**Issue by amervitz** [MicrosoftDocs/power-platform#326]
Please add information that describes how long it is expected to take for a user to be enabled/disabled in an environment after a security group is newly assigned to an environment, as well has after a user is added/removed from a security group already assigned to an environment. It does not appear to be immediate or after 15 minutes. Is this expected to take over an hour or more? Without knowing the expected time, it is hard to tell if the sync is working properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aafd67e-8013-565e-6566-9773136c4405
* Version Independent ID: 1db48adc-6512-7978-4656-2cf081b5cdb7
* Content: [Control user access to environments: security groups and licenses - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/control-user-access)
* Content Source: [power-platform/admin/control-user-access.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/control-user-access.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by deepalakhani** [comment]
How long does it take for the members of the security group to get added to the environment?  Do we have any update on this?

**Comment by jayasreekumar** [comment]
Security group membership sync latency depends on whether the environment is onboarded to the new user sync service, the size of the security group itself and the geo where the environment is. Administrative actions at security group level (example: role management) can be done without waiting for user sync to complete since these security changes will take effect at run time, triggering just-in-time user sync. Would be happy to jump on a call with you to understand the scenarios for your organization that need user sync and provide appropriate suggestions.
