### ISSUE TITLE
Sentence doesn't look right

### ISSUE THREAD

**Issue by PathToSharePoint** [MicrosoftDocs/power-platform#394]
Hello,

I am reading this:
it's often best to define a single publisher so you can change the layering model across publishers later.

This doesn't  make much sense to me, I assume it should say "across solutions"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed97a28-1e40-eaca-1612-367a71f7d0d7
* Version Independent ID: a1201bae-0aa1-6350-63d5-f2aecdc4eacb
* Content: [Solution concepts - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/solution-concepts-alm#solution-publisher)
* Content Source: [power-platform/alm/solution-concepts-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/solution-concepts-alm.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by PathToSharePoint** [comment]
After more reading, I think it actually means to read "across environments".

**Comment by Mattp123** [comment]
@PathToSharePoint - thank you for your feedback. You were correct the first time that it should be "across solutions." The last two sentences in the paragraph for the article has been revised as follows: 
Once you introduce a publisher for a component in a managed solution, you can’t change the publisher for the component. Because of this, it's best to define a single publisher so you can change the layering model across solutions later.

Closing issue.
