### ISSUE TITLE
Incorrect order?

### ISSUE THREAD

**Issue by jonathankhootek** [MicrosoftDocs/power-platform#400]
if you need require a minimum set of privileges for a role, and you need to copy those from the imported solution, shouldn't the solution import step come first? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4508e9-6043-3bad-080a-956f5febb92b
* Version Independent ID: 726691e0-81c1-f3d3-d8f2-6eddecb21753
* Content: [Configure user security in an environment - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/database-security#create-or-configure-a-custom-security-role)
* Content Source: [power-platform/admin/database-security.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/database-security.md)
* Service: **power-platform**
* GitHub Login: @jayasreekumar
* Microsoft Alias: **jkumar**

**Comment by jimholtz** [comment]
@jonathankhootek 
If the question is "I don’t have the privilege at all, then shouldn’t I import the solution first?", the answer is ‘No’, because you need privileges to log in to and privileges to Import Solution.  This article assumes an admin who we expect to have the appropriate privileges to create a security role.
