### ISSUE TITLE
Duplicate Custom Connector

### ISSUE THREAD

**Issue by eBentl** [MicrosoftDocs/power-platform#459]
At present the Office 365 Management API custom connector is included in both the Core solution and the Audit Log solution, configuring the custom connector prior to importing the Audit Log solution appears to create duplicate connectors or otherwise interfere with the connector configuration.

Recommend changing the instructions to import the Audit Log solution prior to configuring the Custom Connector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1855a9ee-8713-c8e6-2091-bc972f877c13
* Version Independent ID: c87a0108-4de6-49df-8ba3-3bdb06216ad8
* Content: [Set up audit log components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
* Content Source: [power-platform/guidance/coe/setup-auditlog.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-auditlog.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
The Audit Log connector is only present in the Core solution, and has been removed from the Audit Log solution. This is due to having moved to using connection references - connection references require a custom connector being present in the environment before establishing a connection to it during solution import. If you upgrade both solutions, you will only have one custom connector.
