### ISSUE TITLE
Rollup fields and calculated fields are they counted against entitlement limits. ?

### ISSUE THREAD

**Issue by malaker** [MicrosoftDocs/power-platform#465]
Hi

I am wondering whether calculated fields and rollup fields are counted against entitlement limits ?

Does anyone know something more about it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f2c989-54cf-d81a-aafb-2f4cd6fef108
* Version Independent ID: 69811228-6a61-a078-86b3-ed11a6d9c84d
* Content: [Requests limits and allocations - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)
* Content Source: [power-platform/admin/api-request-limits-allocations.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/api-request-limits-allocations.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by JimDaly** [comment]
You can learn more about _**service protection limits**_ by clicking the link on this page that will take you to this topic:
[Service Protection API Limits](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/api-limits)

Service protection limits are very different from Entitlement limits. 
For CDS specifically, this page breaks it down: [Common Data Service API limits overview](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview)

For example, 

- Service protection limits apply to ALL requests. Entitlement limits only apply to entity CRUD operations.
- Service protection limits are evaluated in a 5 minute sliding window. Entitlement limits are evaluated in a 24 hour period.

But to answer your question: Rollup and calculated fields are not counted against _service protection limits_ because these are initiated internally.

But if your question is actually about _Entitlement limits_ (because that is the main focus of this topic) then someone else should respond.

**Comment by malaker** [comment]
@JimDaly  Thanks for answer 

Yea I mixed two things. Of course I meant entitlement limits.

**Comment by JimDaly** [comment]
You might want to post your feedback on this page: 
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview
The [Entitlement Limits](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/api-limits-overview#entitlement-limits) section provides more details and new details could be added to address your question.

It is specific to CDS, and Rollup and Calculated fields are specific to CDS.
This topic takes a broader Power Platform scope, so it may not get into CDS specific issues.

As I understand it, the entitlement limits accrue to the user who performed the operation. So the question is: Are the Rollup and Calculated fields considered to be initiated by the calling user? 
Calculated fields are computed on a Retrieve call. Rollup fields are calculated by asynchronous jobs.
Neither are directly part of the request initiated by the user. But I'll let the people who own Entitlement limits respond. Not my specific area of expertise.
