### ISSUE TITLE
CoE Settings missing in current release

### ISSUE THREAD

**Issue by sabrinahota** [MicrosoftDocs/power-platform#485]
Hi all, 
I am currently installing the CoE Starter Kit and the "Configure CoE Settings" page is missing in the current release. 

Has it been moved to somewhere else, or just removed? See attachment. 

Thank you!

![image](https://user-images.githubusercontent.com/48095824/100179188-c00e3380-2ed5-11eb-8ea1-f08254fec064.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Guten Morgen :) 

We have seen this issue before in environments where English was not set up as a language - it then seems the navigation gets confused. Let me walk you through some steps on how to fix that.

1. Go to make.powerapps.com > Solutions > Center of Excellence - Core Components solution
2. Find the Power Platform Admin View - Site Map
![image](https://user-images.githubusercontent.com/55705669/100208530-bcdc6d00-2f00-11eb-9739-72cec39b5e4b.png)
3. Here you will see the different Navigation Groups that should be available, but in your case they will all read "Neue Gruppe" - because the name isn't unique, when the app is played it will only show the first navigation group
![image](https://user-images.githubusercontent.com/55705669/100208543-c1a12100-2f00-11eb-9914-adb86c668f7a.png)
4. Go ahead and change the Group names to Monitor, People and CoE Settings (or feel free to pick different names, as long as they're unique per group)
5. Select Save and then Publish in the right hand corner
![image](https://user-images.githubusercontent.com/55705669/100208770-ff9e4500-2f00-11eb-9666-76e43ada2ce1.png)

If you open the app again now, you should see all navigation groups. Let me know if that works!
