### ISSUE TITLE
step by step error or missing step

### ISSUE THREAD

**Issue by Philippe-ecomcs** [MicrosoftDocs/power-platform#630]
Missing connection => Notification

Step 11 var environment never asked ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Installer les composants principaux - Power Platform](https://docs.microsoft.com/fr-fr/power-platform/guidance/coe/setup-core-components#feedback)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform-pr.fr-FR/blob/live/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment]
Hello,

thanks for letting us know - looks like we left some Default values in for Environment Variables in our latest release, which is why you're not prompted to fill them out during Setup. You can follow these steps to update them after install https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables 

Will fix this in our next release!

Thank you for using the CoE
Manuela
