### ISSUE TITLE
Unclear whether provided GUIDs for Teams client and Web app are examples

### ISSUE THREAD

**Issue by DmitryVorobyov** [MicrosoftDocs/power-platform#851]
**Section**: [https://docs.microsoft.com/en-us/power-virtual-agents/configure-sso-teams?source=docs#add-authorized-client-app-ids](url)

_Remember to replace the example IDs and values below with your own Azure AD configured values._

It is unclear whether _1fec8e78-bce4-4aaf-ab1b-5451cc387264_ and _5e3ce6c0-2b1f-4285-8d4b-75ee78787346_ are example IDs or actual values that need to be entered. 

**If they are examples, please add instructions on how to find actual values.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 965f620e-95eb-f98d-b128-ccd80c7002e8
* Version Independent ID: b96dc7d3-51c7-1f9b-e82a-282e56941770
* Content: [Configure single sign-on for the Power Virtual Agents app in Teams - Power Virtual Agents](https://docs.microsoft.com/en-us/power-virtual-agents/configure-sso-teams?source=docs#feedback)
* Content Source: [power-virtual-agents/configure-sso-teams.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-virtual-agents/configure-sso-teams.md)
* Service: **power-virtual-agents**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by iaanw** [comment]
@clmori can you confirm if the values for the Teams apps are actual IDs and not examples? I'm fairly sure they are the actual IDs but want to double check. If they are, then I suggest we remove the Note just above that talks about replacing examples IDs because it's confusing, and I might do a bit of a rework of the rest of the instructions to clarify which are examples and which aren't (also, we should probably scrub the screenshots). Let me know what you think, thanks!
