### ISSUE TITLE
SetNonBusinessDataGroupState not blocking connections

### ISSUE THREAD

**Issue by devinprejean** [MicrosoftDocs/power-platform#86]
The new addition of the SetNonBusinessDataGroupState doesn't seem to do anything besides put the word "Blocked" in the DLP. I have checked previously created apps, new apps, and event deleted the existing connections to make new connections. All connectors that were supposed to be blocked had absolutely no issue being created and even published.

Is there a proper way to use this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform Admin center](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell#feedback)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@devinprejean 
From the product team:
There’s a delay of a few hours after the block is set for it to take effect. If the customer sees the word “blocked” in the DLP UI then it looks like it’s being used correctly and should work after a few hours.

We'll get this documented after future testing.

**Comment by devinprejean** [comment]
Thanks for taking a look at this so soon @jimholtz ,
Well I've went back to see today (2 days later) and it's not blocking. I have left SharePoint, onedrive, and mail in the blocked category and it's allowing me to use them no problem.

I would assume one could not even make a connection if the connector is blocked when this is turned on. What does Microsoft expect the behavior to be?

**Comment by jimholtz** [comment]
@devinprejean 
From the product team,
Expected behavior is:
You cannot add a blocked connector to a new Power App. An existing Power App that already uses that connector can still be run, even though it contains a connector that’s blocked.
You can add a blocked connector to a flow, but when that flow is saved it will be disabled and cannot be run. An existing flow with that connector can still be run until it is re-saved/edited, at which point the block should take effect and disable the flow.
If the customer isn’t experiencing this behavior they should contact support.

**Comment by devinprejean** [comment]
Thank you @jimholtz  that is not the case here. I will contact support.
