### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by nick-corsair** [MicrosoftDocs/power-platform#926]
There are multiple "Power Apps per app plan".  Where would one go (if not this page) to find the difference between "Power Apps per app plan" and "Power Apps per app plan (1 app or portal)"?  Both show up under the licensing purchase options with no difference in description between them other than 30 minimum licenses are needed for "Power Apps per app plan" which is not documented anywhere in here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1f9ece-05b6-907c-9d52-5a19f5bf9872
* Version Independent ID: 9eaed30a-4c07-ef03-e3b4-d3db9989a760
* Content: [About Power Apps per app plans - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp)
* Content Source: [power-platform/admin/about-powerapps-perapp.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/about-powerapps-perapp.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment]
@nick-corsair 
You're seeing two options because you've purchased the ‘old’ per app plan in the past and have 6 months to continue to do so. Please the Licensing FAQ: https://businessapplications.transform.microsoft.com/ and https://docs.microsoft.com/en-us/power-platform/admin/about-powerapps-perapp#step-one-purchase-per-app-plans.
