### ISSUE TITLE
Wrong Syntax in my Canvas Apps

### ISSUE THREAD

**Issue by pascalhollmann** [MicrosoftDocs/power-platform#996]
Hi all,

in real live the Syntax seems to be different. 
For example you have this example on the page:
`UpdateContext( { x: 1 } ); Back()`

i have to wirte this like this (with the &)

`UpdateContext( { x: 1 } )& Back()`

next difference....
i cannot use this
`If( Value(TextBox1.Text) >= 0, Color.Black, Color.Red )`

i have to use ;

`If( Value(TextBox1.Text) >= 0; Color.Black; Color.Red )`

Is this a setting or related to the language? What is the Problem in my enviroments?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: af3e0499-2af3-ce76-bf10-3dcf3cda8112
* Version Independent ID: bce3c5df-4008-8d9a-a32a-2e5f5572ae2e
* Content: [Grundlegendes zu imperativer Logik in Microsoft Power Fx - Power Platform](https://docs.microsoft.com/de-de/power-platform/power-fx/imperative)
* Content Source: [power-platform/power-fx/imperative.md](https://github.com/MicrosoftDocs/power-platform-pr.de-DE/blob/live/power-platform/power-fx/imperative.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by jorisdg** [comment]
This is related to your user language. For languages that use a comma ( , ) as a decimal separator, hardcoding a number would be 1,23 instead of 1.23 for locales where a dot ( . ) is the decimal separator.
Because the comma is now used for numbers, the syntax to separate arguments switches to use using semi-colons, as you have found out. Semi-colons in behavior functions become double semicolon ( ;; )

We used to have localized code samples and recently found out this is no longer being done. We're looking into integrating that again so code samples are relevant to the language you are reading the documentation.

I hope this helps explain. I think we should be able to get back to localized code examples in the future.
